server:
  servlet:
    context-path: /api
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/wc
    username: postgres
springdoc:
  swagger-ui:
    path: /
    display-operation-id: true
    disable-swagger-default-url: true
    tags-sorter: alpha
    operations-sorter: alpha
