name: CD

on:
  push:
    branches: main

jobs:
  build:
    runs-on: self-hosted
    env:
      PROFILE: prod
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: mvn clean install
      - name: deploy
        run: docker-compose up -d --build
